name: Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
            version: 8.10.5
      - uses: actions/setup-node@v3
        with:
            node-version: '18'
            cache: 'pnpm'
      - run: pnpm install
      - name: Apply all pending migrations to the database
        run: pnpm prisma migrate deploy
        env:
          POSTGRES_PRISMA_URL: ${{ secrets.POSTGRES_PRISMA_URL }}
          POSTGRES_URL_NON_POOLING: ${{ secrets.POSTGRES_URL_NON_POOLING }}
